// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createClothingItem = `-- name: CreateClothingItem :one
INSERT INTO items (
  id, user_id, image_url, category, processing_status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, image_url, category, color, confidence, processed_image_url, processing_status, created_at
`

type CreateClothingItemParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	ImageUrl         string    `json:"image_url"`
	Category         string    `json:"category"`
	ProcessingStatus string    `json:"processing_status"`
}

func (q *Queries) CreateClothingItem(ctx context.Context, arg CreateClothingItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createClothingItem,
		arg.ID,
		arg.UserID,
		arg.ImageUrl,
		arg.Category,
		arg.ProcessingStatus,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageUrl,
		&i.Category,
		&i.Color,
		&i.Confidence,
		&i.ProcessedImageUrl,
		&i.ProcessingStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getClothingItem = `-- name: GetClothingItem :one
SELECT id, user_id, image_url, category, color, confidence, processed_image_url, processing_status, created_at FROM items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClothingItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getClothingItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageUrl,
		&i.Category,
		&i.Color,
		&i.Confidence,
		&i.ProcessedImageUrl,
		&i.ProcessingStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listClothingByUser = `-- name: ListClothingByUser :many
SELECT id, user_id, image_url, category, color, confidence, processed_image_url, processing_status, created_at FROM items
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClothingByUser(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listClothingByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.Category,
			&i.Color,
			&i.Confidence,
			&i.ProcessedImageUrl,
			&i.ProcessingStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClothingStatus = `-- name: UpdateClothingStatus :exec
UPDATE items
SET processing_status = $2
WHERE id = $1
`

type UpdateClothingStatusParams struct {
	ID               uuid.UUID `json:"id"`
	ProcessingStatus string    `json:"processing_status"`
}

func (q *Queries) UpdateClothingStatus(ctx context.Context, arg UpdateClothingStatusParams) error {
	_, err := q.db.Exec(ctx, updateClothingStatus, arg.ID, arg.ProcessingStatus)
	return err
}
