// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	ImageUrl          string             `json:"image_url"`
	Category          string             `json:"category"`
	Color             string             `json:"color"`
	Confidence        float64            `json:"confidence"`
	ProcessedImageUrl pgtype.Text        `json:"processed_image_url"`
	ProcessingStatus  string             `json:"processing_status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
