// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, user_id, image_url, category, color, confidence) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, user_id, image_url, category, color, confidence, processed_image_url, processing_status, created_at
`

type CreateItemParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ImageUrl   string    `json:"image_url"`
	Category   string    `json:"category"`
	Color      string    `json:"color"`
	Confidence float64   `json:"confidence"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.UserID,
		arg.ImageUrl,
		arg.Category,
		arg.Color,
		arg.Confidence,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageUrl,
		&i.Category,
		&i.Color,
		&i.Confidence,
		&i.ProcessedImageUrl,
		&i.ProcessingStatus,
		&i.CreatedAt,
	)
	return i, err
}
