// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClothingItem(ctx context.Context, arg CreateClothingItemParams) (Item, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetClothingItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListClothingByUser(ctx context.Context, userID uuid.UUID) ([]Item, error)
	UpdateClothingStatus(ctx context.Context, arg UpdateClothingStatusParams) error
}

var _ Querier = (*Queries)(nil)
