// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: share.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO shared_wardrobes (user_id, slug, expires_at)
VALUES ($1, $2, $3) -- Changed from NOW()... to $3 so Go can control it
RETURNING id, user_id, slug, expires_at, created_at
`

type CreateShareLinkParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Slug      string             `json:"slug"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (SharedWardrobe, error) {
	row := q.db.QueryRow(ctx, createShareLink, arg.UserID, arg.Slug, arg.ExpiresAt)
	var i SharedWardrobe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySlug = `-- name: GetUserBySlug :one
SELECT user_id FROM shared_wardrobes
WHERE slug = $1 AND expires_at > NOW()
`

func (q *Queries) GetUserBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserBySlug, slug)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
