// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
)

const listItems = `-- name: ListItems :many
SELECT id, user_id, image_url, category, color, confidence, created_at FROM items
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.Category,
			&i.Color,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategory = `-- name: ListItemsByCategory :many
SELECT id, user_id, image_url, category, color, confidence, created_at FROM items
WHERE category = $1
ORDER BY created_at DESC
`

func (q *Queries) ListItemsByCategory(ctx context.Context, category string) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageUrl,
			&i.Category,
			&i.Color,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
