// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID         uuid.UUID          `json:"id"`
	UserID     string             `json:"user_id"`
	ImageUrl   string             `json:"image_url"`
	Category   string             `json:"category"`
	Color      string             `json:"color"`
	Confidence float64            `json:"confidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
